language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - rey.webhouse.net
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- openssl aes-256-cbc -K $encrypted_066ac82086cf_key -iv $encrypted_066ac82086cf_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/service-deploy.sh dev $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: bash scripts/service-deploy.sh master $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - cb@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: gUnGuVhbj1X7VoOx1zEELFNq4vNFY0UyawuEb8/V2y7dubwr9N11g/vR1dVO0v07W/K1gWctx6tttxdytJTGcRYvF7IdMOrGPzRdXx/prUOOuW8oonMRV4CGYxzf28dzFxIdpWqmrjJn4CpY8vzZxM/eeOTngaVMfCi/PhdYhS741udZOt7l3QDXJ1T2abcvogPMTwpAT6GLCrl58tHv5y0zKIEfvjeTI0Ixb6IvYKKYcwvEBWhzLu43/6HOPrHNHnvK9luOXPW7a0eTSK1GHsSEErQxW869/N1it99Fld5tQTWiwbB0XlE0vn39Bv8Dx1j8Y5Bvr2tXQJZwRUCFL5OAoNDOSZVjQc1Pv61apZfMClN+9ywJhZmPSx+8SSsOkrDtCD1rbIDCO/IvoksmxTxh1adCBe0hmvHVDtohCmbyD5PlCNAtu2WYJt0yGAEngwEF5ph5B/elIRuMOO8MY0boRze/qBivneyLA95yqOFsn4e3Lfbp0kI5l9i+HGarItoa5XGUDYFoGPDRPmJBW4RtVTIe0F/PVw3h6bweNSwN4hzaWjWsXApTzhFJIJibUSqiOBbJ207HCG5fq73HWbF8OCxz+7XmtbNncxi7HY4KkKEjzi+kNplKW5KuR8S5wwwuhpAlsvGN0liCRmSaNrKof6ufAW1eCUZBphnAPpM=

# Senti SSH deployment with Travis CI

# ssh-keygen -t rsa -b 4096 -C 'senti-service' -f ./deploy_rsa
# travis encrypt-file ./deploy_rsa --add

# If ssh-copy denies you access, manually copy the public key to authorized_keys in .ssh on the server
# ssh-copy-id -i ./deploy_rsa.pub deploy@organa.webhouse.net

# Remember to remove the public keys
# rm -f deploy_rsa deploy_rsa.pub

# Add the files to your Git repository
# git add deploy_rsa.enc .travis.yml
